### ISSUE TITLE
corals not replicating

### ISSUE THREAD

**Issue by cpdef** [Elkien3/citysim_game#2]
i have written a little abm to make corals replicate
chance and interval can be changed
and idk in which mod it should be placed

    minetest.register_abm({
        nodenames = {"default:coral_skeleton"},
        neighbors = {"water"},
        interval = 300,
        chance = 5,
        action = function(pos, node)
                local pos = minetest.find_node_near(pos, 1, "default:water_source")
                if pos == nil then return end
                pos.y = pos.y+1
                if minetest.get_node(pos).name ~= "default:water_source" then return end
                pos.y = pos.y-1
                if math.random(1,2) == 1 then
                        minetest.set_node(pos, { name = "default:coral_brown" })
                else
                        minetest.set_node(pos, { name = "default:coral_orange" })
                end
        end,
    })

**Comment by Elkien3** [comment]
Added
