### ISSUE TITLE
What are the licenses for walking_light and betterfall?

### ISSUE THREAD

**Issue by zaoqi** [Elkien3/citysim_game#26]
I cannot find the license file.

**Comment by Elkien3** [comment]
the original forum post with walking_light says "Code: WTFPL, textures: CC BY-SA" I guess I'm not sure what betterfall's license is, I don't remember if it's new code or edited from https://github.com/Noodlemire/clumpfall/blob/master/LICENSE.txt

**Comment by zaoqi** [comment]
betterfall looks like new code

**Comment by zaoqi** [comment]
ping @aegroto

**Comment by aegroto** [comment]
I've never even bothered adding a license. Consider it public domain and, if you like it, credit me.
